[build]
  base = "health-info-237"
  command = "chmod +x build.sh && ./build.sh"
  publish = "www"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 